### PR TITLE
DEMO-91: Add TagBundle to eZ Studio Demo

### PR DESCRIPTION
**Pull request by damianz5**
https://jira.ez.no/browse/DEMO-91

required by https://github.com/ezsystems/ezstudio-demo-bundle/pull/173

### CODE REVIEW

**Comment by andrerom** [comment]
@SylvainGuittard updated composer to reflect that stable is out ;)

**Comment by SylvainGuittard** [comment]
Thanks @andrerom

**Comment by emodric** [comment]
Not cool, removing the TagsBundle logo!

**Comment by rolandbenedetti** [comment]
@emodric and thumb uppers: come on, it's not a matter of cool or not cool, it's about simple UX. We're really happy to push Netgen and the tag bundle, but we end up with two logos on the two first lines, one on the 1s navigation bar, and then it's adding up an additional horizontal dark row that takes quite some real estate and that's useless in my opinion. Actually that's why we would have love to work a bit more on the u.i. integration with you, but we could fine tune next iteration. If the demo looks like a christmas tree, it's not that great. Are you happier if the top logo goes purple and indicates Netgen??? Is that what you want. 
It could also go in the footer where it would also less hurt the interface.

**Comment by ilukac** [comment]
@rolandbenedetti Agreed on the UX comments and footer idea is nice.  We should go that route.

**Comment by emodric** [comment]
@rolandbenedetti It would've been cool to work with us so we can find the best solution together, and not flat out removing the brand, my comment was referring to that.

**Comment by rolandbenedetti** [comment]
@emodric we kind of tried to have @inakijv involved in there, and tried to use new U.I. guidelines, but it was hard to find time for everybody, so this ended up being done in two separated path but faster (which is cool). Let's do better next time.

**Pull request merged**
