### PR TITLE
EZEE-1382 Add custom filters to a request to eZ Recommendation

### PR DESCRIPTION
**Pull request by kamilmusial**
JIRA: https://jira.ez.no/browse/EZEE-1382

### CODE REVIEW

**Comment by kamilmusial** [comment]
related to https://github.com/ezsystems/EzSystemsRecommendationBundle/pull/87

**Comment by micszo** [comment]
@kamilmusial the last scenario failed because the `restoreStudioDatabase` tag requires _behat_ environment which hasn't been set for this repo yet (it's still _prod_). This was initially tested in formBuilder repo and needs to be propagated to other repos / CI jobs. \cc @mnocon

**Comment by kamilmusial** [comment]
@micszo so... Merge?

**Comment by micszo** [comment]
Yes, it's unrelated.

**Pull request merged**
