### PR TITLE
EZEE-1584: Update composer.json after 1.10 branch created

### PR DESCRIPTION
**Pull request by micszo**
Jira: https://jira.ez.no/browse/EZEE-1584

Discovered in https://github.com/ezsystems/ezstudio-form-builder/pull/158.

### CODE REVIEW

**Comment by andrerom** [comment]
please reopen on `ezplatform` repo

**Comment by lserwatka** [comment]
@andrerom but ezplatform and ezplatform-ee are not affected. There, composer.json has ^1.9 so it will pick up 1.10 component version. Only -demo is affected.

**Comment by andrerom** [comment]
ah, are we missing a merge up, or are you on purpose using `~` ?

**Comment by andrerom** [comment]
And does this imply demo 1.10 and 1.10.1 shipped with 1.9 packages, meaning things like tables some other features are then missing from sales demo?

**Comment by lserwatka** [comment]
Everything is up to date. In demo it is on purpose as we need to limit to certain version of the component (stable branch).

**Comment by lserwatka** [comment]
No, composer.json in ezplatform has not been updated when it comes to major versions, but only composer.lock contains up to date package version. This might be confusing.

**Comment by micszo** [comment]
@vidarl did you change the environment to _behat_ for this meta repo also or only for all jobs with bundles? 🙂 Double-checking because the scenarios with restoring db keeps failing. \cc @mnocon

**Comment by vidarl** [comment]
It was supposed to be fixed for meta repos too. But due to your question I checked the jenkins config.

Turns out that code change never reached this jenkins project because the "git pull" statement was commented out in the config.....

Fixed this and restarted ezrobot

**Comment by micszo** [comment]
@lserwatka I think it's ready.

**Pull request merged**
